apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: webapp
  endpoints:
  - port: web
    path: /metrics
